<?php

namespace Database\Factories;

use App\Models\Booking;
use App\Models\MeetingRoom;
use App\Models\User;
use Illuminate\Database\Eloquent\Factories\Factory;

/**
 * @extends \Illuminate\Database\Eloquent\Factories\Factory<\App\Models\Booking>
 */
class BookingFactory extends Factory
{
    /**
     * Define the model's default state.
     *
     * @return array<string, mixed>
     */
    public function definition(): array
    {
        $startDatetime = fake()->dateTimeBetween('now', '+30 days');
        $endDatetime = (clone $startDatetime)->modify('+'.fake()->numberBetween(1, 4).' hours');

        $decorationThemes = config('booking.decoration_themes', [
            'ธรรมดา (ไม่มีการตกแต่ง)',
            'ธีมธุรกิจ (Business Theme)',
            'ธีมสีฟ้า - ขาว',
            'ธีมดอกไม้สด',
        ]);

        return [
            // booking_ref will be auto-generated by model's creating event
            'user_id' => User::factory(),
            'room_id' => MeetingRoom::factory(),
            'start_datetime' => $startDatetime,
            'end_datetime' => $endDatetime,
            'attendee_count' => fake()->numberBetween(5, 50),
            'decoration_theme' => fake()->optional(0.7)->randomElement($decorationThemes),
            'status' => 'confirmed',
            'notes' => fake()->optional(0.5)->sentence(),
        ];
    }

    /**
     * Indicate that the booking is confirmed.
     */
    public function confirmed(): static
    {
        return $this->state(fn (array $attributes) => [
            'status' => 'confirmed',
        ]);
    }

    /**
     * Indicate that the booking is cancelled.
     */
    public function cancelled(): static
    {
        return $this->state(fn (array $attributes) => [
            'status' => 'cancelled',
        ]);
    }

    /**
     * Indicate that the booking is completed.
     */
    public function completed(): static
    {
        return $this->state(fn (array $attributes) => [
            'status' => 'completed',
        ]);
    }

    /**
     * Create a booking for a specific user.
     */
    public function forUser(User $user): static
    {
        return $this->state(fn (array $attributes) => [
            'user_id' => $user->id,
        ]);
    }

    /**
     * Create a booking for a specific room.
     */
    public function forRoom(MeetingRoom $room): static
    {
        return $this->state(fn (array $attributes) => [
            'room_id' => $room->id,
        ]);
    }

    /**
     * Create a booking for today.
     */
    public function today(): static
    {
        $startDatetime = now()->setHour(fake()->numberBetween(9, 16));
        $endDatetime = (clone $startDatetime)->modify('+'.fake()->numberBetween(1, 4).' hours');

        return $this->state(fn (array $attributes) => [
            'start_datetime' => $startDatetime,
            'end_datetime' => $endDatetime,
        ]);
    }

    /**
     * Create a booking for tomorrow.
     */
    public function tomorrow(): static
    {
        $startDatetime = now()->addDay()->setHour(fake()->numberBetween(9, 16));
        $endDatetime = (clone $startDatetime)->modify('+'.fake()->numberBetween(1, 4).' hours');

        return $this->state(fn (array $attributes) => [
            'start_datetime' => $startDatetime,
            'end_datetime' => $endDatetime,
        ]);
    }
}
